create table pokemon (
nm_pokedex int unique primary key auto_increment,
nome varchar(45),
tipo varchar(45),
descricao varchar(300), 
altura double, 
peso double, 
habilidades varchar (100),
lendario bool);

INSERT INTO pokemon (nome, tipo, descricao, altura, peso, habilidades, lendario)
VALUES
('Bulbasaur', 'Planta/Venenoso', 'Bulbasaur pode ser encontrado nas florestas e pântanos.', 0.7, 6.9, 'Overgrow, Chlorophyll', FALSE),
('Ivysaur', 'Planta/Venenoso', 'Ivysaur começa a mostrar sua evolução com suas folhas crescendo.', 1.0, 13.0, 'Overgrow, Chlorophyll', FALSE),
('Venusaur', 'Planta/Venenoso', 'Venusaur possui uma enorme flor em suas costas que libera pólen.', 2.0, 100.0, 'Overgrow, Chlorophyll', FALSE),
('Charmander', 'Fogo', 'Charmander tem uma chama na ponta de sua cauda que indica sua saúde e disposição.', 0.6, 8.5, 'Blaze', FALSE),
('Charmeleon', 'Fogo', 'Charmeleon tem uma cauda de fogo mais intensa e se torna mais agressivo.', 1.1, 19.0, 'Blaze', FALSE),
('Charizard', 'Fogo/Voador', 'Charizard pode voar e lançar poderosos ataques de fogo.', 1.7, 90.5, 'Blaze', FALSE),
('Squirtle', 'Água', 'Squirtle pode se esconder em sua casca para se proteger de ataques.', 0.5, 9.0, 'Torrent', FALSE),
('Wartortle', 'Água', 'Wartortle tem uma cauda espessa que utiliza para atacar.', 1.0, 22.5, 'Torrent', FALSE),
('Blastoise', 'Água', 'Blastoise possui canhões de água em suas costas que pode usar para atacar.', 1.6, 85.5, 'Torrent', FALSE),
('Caterpie', 'Inseto', 'Caterpie pode se camuflar facilmente em plantas para evitar predadores.', 0.3, 2.9, 'Shield Dust', FALSE),
('Metapod', 'Inseto', 'Metapod é a fase de transição entre Caterpie e Butterfree.', 0.7, 9.9, 'Shed Skin', FALSE),
('Butterfree', 'Inseto/Voador', 'Butterfree pode voar por grandes distâncias, utilizando suas asas coloridas.', 1.1, 32.0, 'Compound Eyes, Tinted Lens', FALSE),
('Weedle', 'Inseto/Venenoso', 'Weedle pode usar seu ferrão venenoso para se defender.', 0.3, 3.2, 'Shield Dust', FALSE),
('Kakuna', 'Inseto/Venenoso', 'Kakuna é a fase de transição entre Weedle e Beedrill.', 0.6, 10.0, 'Shed Skin', FALSE),
('Beedrill', 'Inseto/Venenoso', 'Beedrill usa seus ferrões venenosos para atacar com precisão.', 1.0, 29.5, 'Swarm', FALSE),
('Pidgey', 'Normal/Voador', 'Pidgey é encontrado com frequência em áreas urbanas e florestas.', 0.3, 1.8, 'Keen Eye', FALSE),
('Pidgeotto', 'Normal/Voador', 'Pidgeotto é um Pokémon veloz que pode enfrentar grandes adversários no céu.', 1.1, 30.0, 'Keen Eye', FALSE),
('Pidgeot', 'Normal/Voador', 'Pidgeot é o rei dos céus, com asas poderosas e grande velocidade.', 1.5, 39.5, 'Keen Eye', FALSE),
('Rattata', 'Normal', 'Rattata é conhecido por sua velocidade, mas pode ser facilmente capturado.', 0.3, 3.5, 'Run Away', FALSE),
('Raticate', 'Normal', 'Raticate é um Pokémon agressivo que pode usar sua mandíbula para atacar.', 0.7, 7.5, 'Run Away', FALSE),
('Spearow', 'Normal/Voador', 'Spearow é um pássaro territorial que se torna agressivo se ameaçado.', 0.3, 2.0, 'Keen Eye', FALSE),
('Fearow', 'Normal/Voador', 'Fearow é capaz de voar a altas velocidades, perseguindo suas presas.', 1.2, 38.0, 'Keen Eye', FALSE),
('Ekans', 'Venenoso', 'Ekans é um Pokémon serpente que pode se camuflar facilmente.', 2.0, 6.9, 'Intimidate', FALSE),
('Arbok', 'Venenoso', 'Arbok usa seu corpo longo para enforcar suas presas ou inimigos.', 3.5, 65.0, 'Intimidate', FALSE),
('Pikachu', 'Elétrico', 'Pikachu é um dos Pokémon mais conhecidos, com a habilidade de gerar eletricidade.', 0.4, 6.0, 'Static', FALSE),
('Raichu', 'Elétrico', 'Raichu é a forma evoluída de Pikachu, mais forte e com maior capacidade elétrica.', 0.8, 30.0, 'Static', FALSE),
('Sandshrew', 'Terrestre', 'Sandshrew é um Pokémon que se esconde sob o solo para se proteger de predadores.', 0.6, 12.0, 'Sand Veil', FALSE),
('Sandslash', 'Terrestre', 'Sandslash é um Pokémon com garras afiadas e uma grande habilidade de escavar.', 1.0, 29.5, 'Sand Veil', FALSE),
('Nidoran♀', 'Venenoso', 'Nidoran♀ é conhecido por sua habilidade de atacar com seu ferrão venenoso.', 0.4, 7.0, 'Poison Point', FALSE),
('Nidorina', 'Venenoso', 'Nidorina é a fase evolutiva de Nidoran♀, mais forte e resistente.', 0.8, 20.0, 'Poison Point', FALSE),
('Nidoqueen', 'Venenoso/Terrestre', 'Nidoqueen é um Pokémon forte e protetor, conhecido por sua grande resistência.', 1.3, 60.0, 'Poison Point, Rivalry', FALSE),
('Nidoran♂', 'Venenoso', 'Nidoran♂ é mais agressivo que Nidoran♀, com seu ferrão venenoso.', 0.5, 9.0, 'Poison Point', FALSE),
('Nidorino', 'Venenoso', 'Nidorino é a fase evolutiva de Nidoran♂, com maior força e poder de ataque.', 0.9, 19.5, 'Poison Point', FALSE),
('Nidoking', 'Venenoso/Terrestre', 'Nidoking é uma forma evoluída de Nidorino, com uma grande força física e habilidades de combate.', 1.4, 62.0, 'Poison Point, Rivalry', FALSE),
('Clefairy', 'Fada', 'Clefairy é um Pokémon místico que adora a luz da lua.', 0.6, 7.5, 'Cute Charm', FALSE),
('Clefable', 'Fada', 'Clefable pode usar suas orelhas para detectar sons e vibrações em alta frequência.', 1.3, 40.0, 'Cute Charm, Magic Guard', FALSE),
('Vulpix', 'Fogo', 'Vulpix tem uma cauda composta por seis chamas que usa para atacar seus inimigos.', 0.6, 9.9, 'Flash Fire', FALSE),
('Ninetales', 'Fogo', 'Ninetales possui nove caudas e é capaz de lançar ataques de fogo intensos.', 1.1, 19.9, 'Flash Fire', FALSE),
('Jigglypuff', 'Normal/Fada', 'Jigglypuff pode cantar uma música encantadora que coloca outros Pokémon a dormir.', 0.5, 5.5, 'Cute Charm', FALSE),
('Wigglytuff', 'Normal/Fada', 'Wigglytuff pode cantar canções que hipnotizam todos ao seu redor.', 1.0, 12.0, 'Cute Charm', FALSE),
('Zubat', 'Venenoso/Voador', 'Zubat é um Pokémon que se desloca rapidamente em ambientes escuros usando ecolocalização.', 0.8, 7.5, 'Inner Focus', FALSE),
('Golbat', 'Venenoso/Voador', 'Golbat possui grandes asas que o permitem voar por grandes distâncias.', 1.6, 55.0, 'Inner Focus', FALSE),
('Oddish', 'Planta/Venenoso', 'Oddish se esconde durante o dia e se ativa durante a noite, absorvendo energia solar.', 0.5, 5.4, 'Chlorophyll, Run Away', FALSE),
('Gloom', 'Planta/Venenoso', 'Gloom exala um cheiro horrível que pode paralisar seus inimigos.', 0.8, 8.6, 'Chlorophyll, Stench', FALSE),
('Vileplume', 'Planta/Venenoso', 'Vileplume possui uma enorme flor em sua cabeça que libera esporos tóxicos.', 1.2, 18.6, 'Chlorophyll, Effect Spore', FALSE),
('Paras', 'Inseto/Planta', 'Paras carrega cogumelos nas costas que ajudam a defender o Pokémon de predadores.', 0.3, 5.4, 'Effect Spore', FALSE),
('Parasect', 'Inseto/Planta', 'Parasect tem cogumelos ainda maiores que controlam seu corpo e comportamento.', 1.0, 29.5, 'Effect Spore', FALSE),
('Venonat', 'Inseto/Venenoso', 'Venonat é um Pokémon com olhos grandes que usa para detectar movimentos no escuro.', 0.6, 30.0, 'Compound Eyes', FALSE),
('Venomoth', 'Inseto/Venenoso', 'Venomoth usa suas asas para lançar poeira venenosa que pode envenenar seus inimigos.', 1.5, 12.5, 'Compound Eyes', FALSE),
('Diglett', 'Terrestre', 'Diglett escava túneis subterrâneos e pode aparecer em qualquer lugar.', 0.2, 0.8, 'Sand Veil', FALSE),
('Dugtrio', 'Terrestre', 'Dugtrio é formado por três Digletts, que se movem e atacam juntos.', 0.7, 33.3, 'Sand Veil', FALSE),
('Meowth', 'Normal', 'Meowth é um gato travesso que gosta de colecionar objetos valiosos.', 0.4, 4.2, 'Pickup, Technician', FALSE),
('Persian', 'Normal', 'Persian é um gato elegante e rápido, conhecido por sua grande agilidade.', 1.0, 32.0, 'Pickup, Technician', FALSE),
('Psyduck', 'Água', 'Psyduck sofre de dores de cabeça fortes, mas pode liberar uma grande força quando a dor se intensifica.', 0.8, 19.6, 'Damp', FALSE),
('Golduck', 'Água', 'Golduck possui habilidades psíquicas e pode se mover com grande velocidade.', 1.7, 76.6, 'Damp', FALSE),
('Mankey', 'Lutador', 'Mankey é um Pokémon irascível e sempre pronto para brigar.', 0.5, 28.0, 'Vital Spirit', FALSE),
('Primeape', 'Lutador', 'Primeape é ainda mais agressivo que Mankey e não hesita em atacar.', 1.0, 32.0, 'Vital Spirit', FALSE),
('Growlithe', 'Fogo', 'Growlithe é um Pokémon leal e corajoso, com uma chama ardente em sua cauda.', 0.6, 19.0, 'Intimidate, Flash Fire', FALSE),
('Arcanine', 'Fogo', 'Arcanine é um Pokémon nobre e forte, que pode correr a velocidades impressionantes.', 1.9, 155.0, 'Intimidate, Flash Fire', FALSE),
('Poliwag', 'Água', 'Poliwag tem uma cauda que se move em círculos, o que é um dos seus traços mais característicos.', 0.6, 12.4, 'Torrent, Swift Swim', FALSE),
('Poliwhirl', 'Água', 'Poliwhirl é conhecido por seus poderosos ataques aquáticos e suas habilidades de combate subaquático.', 1.0, 20.0, 'Torrent, Damp', FALSE),
('Poliwrath', 'Água/Lutador', 'Poliwrath é a forma evoluída de Poliwhirl, com uma grande força física e habilidades de combate.', 1.3, 54.0, 'Water Absorb, Damp', FALSE),
('Abra', 'Psíquico', 'Abra usa suas habilidades psíquicas para se teletransportar e evitar ataques.', 0.9, 19.5, 'Synchronize, Inner Focus', FALSE),
('Kadabra', 'Psíquico', 'Kadabra é um Pokémon muito inteligente e poderoso, que usa sua força psíquica para batalhar.', 1.3, 56.5, 'Synchronize, Inner Focus', FALSE),
('Alakazam', 'Psíquico', 'Alakazam é um dos Pokémon mais inteligentes, com habilidades psíquicas poderosas e uma velocidade incrível.', 1.5, 48.0, 'Synchronize, Inner Focus', FALSE),
('Machop', 'Lutador', 'Machop é um Pokémon musculoso e focado em treinamento físico, que utiliza seus punhos em combate.', 0.8, 19.5, 'Guts, No Guard', FALSE),
('Machoke', 'Lutador', 'Machoke é mais forte que Machop, com um poder físico impressionante, capaz de derrotar seus oponentes rapidamente.', 1.5, 70.5, 'Guts, No Guard', FALSE),
('Machamp', 'Lutador', 'Machamp é um Pokémon extremamente forte, com quatro braços para atacar seus inimigos.', 1.6, 130.0, 'Guts, No Guard', FALSE),
('Bellsprout', 'Planta/Venenoso', 'Bellsprout tem um corpo que se assemelha a uma planta carnívora, que utiliza para capturar suas presas.', 0.7, 4.0, 'Chlorophyll, Gluttony', FALSE),
('Weepinbell', 'Planta/Venenoso', 'Weepinbell é um Pokémon que se alimenta de insetos, usando seu corpo flexível para capturá-los.', 1.0, 6.4, 'Chlorophyll, Gluttony', FALSE),
('Victreebel', 'Planta/Venenoso', 'Victreebel usa suas folhas afiadas para caçar e consumir alimentos, com uma habilidade de captura impressionante.', 1.7, 15.5, 'Chlorophyll, Gluttony', FALSE),
('Tentacool', 'Água/Venenoso', 'Tentacool possui tentáculos venenosos que usa para capturar suas presas e se defender de ataques.', 0.9, 35.0, 'Clear Body, Liquid Ooze', FALSE),
('Tentacruel', 'Água/Venenoso', 'Tentacruel é muito mais perigoso que Tentacool, com tentáculos longos e venenosos.', 1.6, 55.0, 'Clear Body, Liquid Ooze', FALSE),
('Geodude', 'Pedra/Terrestre', 'Geodude é um Pokémon robusto e resistente, com um corpo formado por pedras e capaz de atacar com força bruta.', 0.4, 20.0, 'Rock Head, Sturdy', FALSE),
('Graveler', 'Pedra/Terrestre', 'Graveler tem um corpo mais forte e pesado que Geodude, sendo capaz de se mover rapidamente em terrenos rochosos.', 1.0, 105.0, 'Rock Head, Sturdy', FALSE),
('Golem', 'Pedra/Terrestre', 'Golem é uma forma mais poderosa de Graveler, com um corpo imenso e enorme força física.', 1.4, 300.0, 'Rock Head, Sturdy', FALSE),
('Ponyta', 'Fogo', 'Ponyta é um Pokémon ágil que possui uma crina e cauda de fogo que se movem rapidamente durante a corrida.', 0.8, 30.0, 'Run Away, Flash Fire', FALSE),
('Rapidash', 'Fogo', 'Rapidash é um Pokémon rápido e com habilidades de corrida impressionantes, que utiliza suas chamas para atacar.', 1.7, 95.0, 'Run Away, Flash Fire', FALSE),
('Slowpoke', 'Água/Psíquico', 'Slowpoke é um Pokémon lento, mas muito forte quando se concentra em batalha.', 1.2, 36.0, 'Oblivious, Own Tempo', FALSE),
('Slowbro', 'Água/Psíquico', 'Slowbro é uma forma evoluída de Slowpoke, que possui um grande poder psíquico e um braço de caracol.', 1.6, 78.5, 'Oblivious, Own Tempo', FALSE),
('Magnemite', 'Elétrico/Metal', 'Magnemite é um Pokémon magnético que usa sua capacidade de gerar campos elétricos para se defender.', 0.3, 6.0, 'Magnet Pull, Sturdy', FALSE),
('Magneton', 'Elétrico/Metal', 'Magneton é formado por três Magnemites unidos por seu campo magnético, o que o torna mais forte e resistente.', 1.0, 60.0, 'Magnet Pull, Sturdy', FALSE),
('Farfetch´d', 'Normal/Voador', 'Farfetch\'d é um Pokémon que carrega um alho-poró como sua arma e símbolo de honra.', 0.6, 15.0, 'Keen Eye, Inner Focus', FALSE),
('Doduo', 'Normal/Voador', 'Doduo é um Pokémon de duas cabeças que corre em grandes velocidades.', 1.4, 39.2, 'Run Away, Early Bird', FALSE),
('Dodrio', 'Normal/Voador', 'Dodrio é uma versão mais forte e agressiva de Doduo, com três cabeças e maior velocidade.', 1.8, 85.2, 'Run Away, Early Bird', FALSE),
('Seel', 'Água', 'Seel é um Pokémon de corpo escorregadio que se move com facilidade pela água.', 1.1, 90.0, 'Thick Fat, Hydration', FALSE),
('Dewgong', 'Água/Gelo', 'Dewgong é um Pokémon ágil na água e nas regiões geladas, com uma bela cauda que se move suavemente.', 1.7, 120.0, 'Thick Fat, Hydration', FALSE),
('Grimer', 'Venenoso', 'Grimer é um Pokémon composto por substâncias tóxicas e nocivas, que pode se moldar conforme seu ambiente.', 0.9, 30.0, 'Stench, Poison Touch', FALSE),
('Muk', 'Venenoso', 'Muk é a forma evoluída de Grimer, com uma substância viscosa e venenosa em seu corpo.', 1.2, 30.0, 'Stench, Poison Touch', FALSE),
('Shellder', 'Água', 'Shellder é um Pokémon com uma concha dura que usa para se proteger e atacar.', 0.3, 4.0, 'Shell Armor', FALSE),
('Cloyster', 'Água/Gelo', 'Cloyster é um Pokémon muito resistente com uma concha imensa que pode disparar tiros de água congelada.', 1.5, 132.5, 'Shell Armor', FALSE),
('Gastly', 'Fantasma/Venenoso', 'Gastly é um Pokémon formado por gás, capaz de desaparecer em sombras e se mover sem ser visto.', 1.3, 0.1, 'Levitate', FALSE),
('Haunter', 'Fantasma/Venenoso', 'Haunter é uma forma mais sólida de Gastly, capaz de atravessar paredes e causar terror em outros Pokémon.', 1.6, 0.1, 'Levitate', FALSE),
('Gengar', 'Fantasma/Venenoso', 'Gengar é um Pokémon sombrio que gosta de pregar peças e causar pesadelos nos outros.', 1.5, 40.5, 'Levitate', FALSE),
('Onix', 'Pedra/Terrestre', 'Onix é um Pokémon grande, formado por pedras e capaz de escavar grandes buracos com sua força.', 8.8, 210.0, 'Rock Head, Sturdy', FALSE),
('Drowzee', 'Psíquico', 'Drowzee é um Pokémon que usa suas habilidades psíquicas para induzir outros a dormir.', 1.0, 32.4, 'Insomnia, Forewarn', FALSE),
('Hypno', 'Psíquico', 'Hypno é uma forma evoluída de Drowzee, com habilidades psíquicas ainda mais poderosas para controlar mentes.', 1.6, 75.6, 'Insomnia, Forewarn', FALSE),
('Krabby', 'Água', 'Krabby é um pequeno Pokémon marinho com uma pinça forte que pode quebrar pedras.', 0.4, 6.5, 'Hyper Cutter, Shell Armor', FALSE),
('Kingler', 'Água', 'Kingler é a forma evoluída de Krabby, com uma pinça gigantesca que pode esmagar qualquer coisa.', 1.3, 60.0, 'Hyper Cutter, Shell Armor', FALSE),
('Voltorb', 'Elétrico', 'Voltorb é um Pokémon com a aparência de uma esfera elétrica, conhecido por sua natureza explosiva.', 0.5, 10.4, 'Static, Soundproof', FALSE),
('Electrode', 'Elétrico', 'Electrode é a forma evoluída de Voltorb, conhecido por sua habilidade em criar explosões elétricas.', 1.2, 66.6, 'Static, Soundproof', FALSE),
('Exeggcute', 'Planta/Psíquico', 'Exeggcute é um grupo de ovos que possui um cérebro coletivo e habilidades psíquicas.', 0.4, 2.5, 'Chlorophyll, Harvest', FALSE),
('Exeggutor', 'Planta/Psíquico', 'Exeggutor tem uma grande cabeça com várias folhas que usa para atacar e defender.', 2.0, 120.0, 'Chlorophyll, Harvest', FALSE),
('Cubone', 'Terrestre', 'Cubone é um Pokémon triste que carrega o crânio de sua mãe como um escudo.', 0.4, 6.5, 'Rock Head', FALSE),
('Marowak', 'Terrestre', 'Marowak é a forma evoluída de Cubone, com uma enorme clava feita do crânio de sua mãe para proteger-se.', 1.0, 45.0, 'Rock Head', FALSE),
('Hitmonlee', 'Lutador', 'Hitmonlee é um Pokémon especializado em ataques de chute, com uma flexibilidade incrível nas pernas.', 1.5, 49.8, 'Limber, Reckless', FALSE),
('Hitmonchan', 'Lutador', 'Hitmonchan é um mestre em ataques de socos, com punhos rápidos e fortes.', 1.4, 50.2, 'Iron Fist, Keen Eye', FALSE),
('Lickitung', 'Normal', 'Lickitung é um Pokémon de língua longa e pegajosa, usada para capturar comida e outros itens.', 1.2, 65.5, 'Own Tempo, Oblivious', FALSE),
('Koffing', 'Venenoso', 'Koffing é um Pokémon que exala fumaça tóxica, sendo perigoso para quem se aproxima dele.', 0.6, 1.0, 'Levitate, Neutralizing Gas', FALSE),
('Weezing', 'Venenoso', 'Weezing tem dois corpos ligados por uma fumaça venenosa, que se expande para atacar seus inimigos.', 1.2, 9.5, 'Levitate, Neutralizing Gas', FALSE),
('Rhyhorn', 'Pedra/Terrestre', 'Rhyhorn é um Pokémon muito forte, com uma enorme horn que usa para se defender e atacar.', 1.0, 115.0, 'Lightning Rod, Rock Head', FALSE),
('Rhydon', 'Pedra/Terrestre', 'Rhydon é a evolução de Rhyhorn, com uma resistência imensa e um grande poder de ataque físico.', 1.9, 120.0, 'Lightning Rod, Rock Head', FALSE),
('Chansey', 'Normal', 'Chansey é um Pokémon que cuida de outros Pokémon e possui habilidades de cura excepcionais.', 1.1, 34.6, 'Natural Cure, Serene Grace', FALSE),
('Tangela', 'Planta', 'Tangela é coberto por uma vasta quantidade de cipós, que usa para se proteger e atacar.', 1.0, 35.0, 'Chlorophyll', FALSE),
('Kangaskhan', 'Normal', 'Kangaskhan é um Pokémon protetor e dedicado, que carrega seu filhote dentro de sua bolsa.', 2.2, 80.0, 'Early Bird', FALSE),
('Horsea', 'Água', 'Horsea é um Pokémon com a aparência de um pequeno cavalo-marinho, famoso por sua habilidade de nadar com agilidade.', 0.4, 8.0, 'Swift Swim, Sniper', FALSE),
('Seadra', 'Água', 'Seadra é a forma evoluída de Horsea, com um corpo mais robusto e habilidades aquáticas aprimoradas.', 1.2, 25.0, 'Swift Swim, Sniper', FALSE),
('Goldeen', 'Água', 'Goldeen é um Pokémon com aparência de peixe dourado, famoso por sua velocidade na água.', 0.6, 15.0, 'Swift Swim, Lightning Rod', FALSE),
('Seaking', 'Água', 'Seaking é um Pokémon ágil na água, conhecido por suas barbatanas e poder de natação.', 1.3, 39.0, 'Swift Swim, Water Veil', FALSE),
('Staryu', 'Água', 'Staryu é um Pokémon estelar que brilha à noite, usando seus poderes psíquicos para se comunicar.', 0.8, 34.5, 'Natural Cure', FALSE),
('Starmie', 'Água/Psíquico', 'Starmie é a forma evoluída de Staryu, com um poder psíquico ainda mais forte e capacidade de controlar a água.', 1.1, 80.0, 'Natural Cure', FALSE),
('Mr. Mime', 'Psíquico/Fada', 'Mr. Mime é um Pokémon de aparência humana que cria barreiras invisíveis com suas mãos.', 1.3, 54.5, 'Soundproof, Filter', FALSE),
('Scyther', 'Inseto/Voador', 'Scyther é um Pokémon ágil e mortal, conhecido por suas lâminas afiadas nas garras e capacidade de voo.', 1.5, 56.0, 'Swarm, Technician', FALSE),
('Jynx', 'Gelo/Psíquico', 'Jynx é um Pokémon que possui habilidades psíquicas e é capaz de controlar a temperatura ao seu redor.', 1.4, 40.6, 'Oblivious, Forewarn', FALSE),
('Electabuzz', 'Elétrico', 'Electabuzz é um Pokémon elétrico com habilidades incríveis de manipulação de eletricidade.', 1.1, 30.0, 'Static, Vital Spirit', FALSE),
('Magmar', 'Fogo', 'Magmar é um Pokémon de chamas vivas, capaz de lançar fogo com seu corpo quente.', 1.3, 44.5, 'Flame Body, Vital Spirit', FALSE),
('Pinsir', 'Inseto', 'Pinsir é um Pokémon forte que usa suas poderosas mandíbulas para capturar e esmagar seus inimigos.', 1.5, 55.0, 'Hyper Cutter, Mold Breaker', FALSE),
('Tauros', 'Normal', 'Tauros é um Pokémon muito agressivo, com uma grande força física e poder de ataque.', 1.4, 88.4, 'Anger Point, Intimidate', FALSE),
('Magikarp', 'Água', 'Magikarp é um Pokémon muito fraco, mas com grande potencial para evoluir em algo incrível.', 0.9, 10.0, 'Swift Swim', FALSE),
('Gyarados', 'Água/Voado', 'Gyarados é um Pokémon feroz, conhecido por sua força incontrolável e habilidade de causar destruição em grandes áreas.', 6.5, 235.0, 'Intimidate, Moxie', FALSE),
('Lapras', 'Água/Gelo', 'Lapras é um Pokémon gentil que transporta pessoas através de grandes distâncias no oceano.', 2.5, 220.0, 'Water Absorb, Shell Armor', FALSE),
('Ditto', 'Normal', 'Ditto é um Pokémon especial que pode se transformar em qualquer outro Pokémon que veja.', 0.3, 4.0, 'Limber', FALSE),
('Eevee', 'Normal', 'Eevee é um Pokémon conhecido por suas várias formas evolutivas, cada uma com diferentes habilidades.', 0.3, 6.5, 'Run Away, Adaptability', FALSE),
('Vaporeon', 'Água', 'Vaporeon é uma das evoluções de Eevee, com habilidades aquáticas excepcionais.', 1.0, 29.0, 'Water Absorb', FALSE),
('Jolteon', 'Elétrico', 'Jolteon é a evolução elétrica de Eevee, com grande velocidade e agilidade.', 0.8, 24.5, 'Volt Absorb', FALSE),
('Flareon', 'Fogo', 'Flareon é a evolução de fogo de Eevee, com grande poder de ataque e controle de chamas.', 0.9, 25.0, 'Flash Fire', FALSE),
('Porygon', 'Normal', 'Porygon é um Pokémon de aparência digital, criado a partir de tecnologia avançada.', 0.8, 36.5, 'Trace', FALSE),
('Omanyte', 'Pedra/Água', 'Omanyte é um Pokémon ancestral que viveu há milhões de anos, com um corpo envolto por uma concha espiralada.', 0.4, 7.5, 'Swift Swim, Infiltrator', FALSE),
('Omastar', 'Pedra/Água', 'Omastar é a evolução de Omanyte, com um corpo mais forte e a habilidade de liberar jatos de água congelada.', 1.0, 35.0, 'Swift Swim, Infiltrator', FALSE),
('Kabuto', 'Pedra/Água', 'Kabuto é um Pokémon pré-histórico que viveu nas profundezas dos mares, com uma concha protetora em seu corpo.', 0.5, 11.5, 'Swift Swim, Battle Armor', FALSE),
('Kabutops', 'Pedra/Água', 'Kabutops é a forma evoluída de Kabuto, com garras afiadas e habilidades ágeis para se mover rapidamente na água e em terra.', 1.3, 40.5, 'Swift Swim, Battle Armor', FALSE),
('Aerodactyl', 'Pedra/Voador', 'Aerodactyl é um Pokémon fossilizado que ressurgiu do passado, com grande velocidade e garras afiadas.', 1.8, 59.0, 'Rock Head, Pressure', FALSE),
('Snorlax', 'Normal', 'Snorlax é um Pokémon gigante que dorme por longos períodos e é muito difícil de acordar.', 2.1, 460.0, 'Immunity, Thick Fat', FALSE),
('Articuno', 'Gelo/Voador', 'Articuno é um lendário Pokémon de gelo que pode controlar as nevascas e tempestades de neve.', 1.7, 55.4, 'Pressure, Ice Body', TRUE),
('Zapdos', 'Elétrico/Voador', 'Zapdos é um lendário Pokémon elétrico, capaz de gerar imensas descargas elétricas que destroem tudo ao seu redor.', 1.6, 52.6, 'Pressure', TRUE),
('Moltres', 'Fogo/Voador', 'Moltres é um lendário Pokémon de fogo, conhecido por seu poder de gerar chamas intensas que iluminam o céu.', 2.0, 60.0, 'Pressure', TRUE),
('Dratini', 'Dragão', 'Dratini é um Pokémon serpente que pode evoluir em poderosos dragões como Dragonite.', 1.8, 3.3, 'Marvel Scale', FALSE),
('Dragonair', 'Dragão', 'Dragonair é uma forma evoluída de Dratini, com grandes habilidades de voo e uma cauda elegante.', 4.0, 16.5, 'Marvel Scale', FALSE),
('Dragonite', 'Dragão/Voador', 'Dragonite é um dragão poderoso, capaz de voar grandes distâncias e mover-se com grande rapidez.', 2.2, 210.0, 'Inner Focus, Multiscale', FALSE),
('Mewtwo', 'Psíquico', 'Mewtwo é um Pokémon lendário criado geneticamente, com grande poder psíquico e habilidades superiores.', 2.0, 122.0, 'Pressure, Unnerve', TRUE),
('Mew', 'Psíquico', 'Mew é um Pokémon raro com poderes psíquicos e a habilidade de aprender qualquer movimento.', 0.4, 4.0, 'Synchronize', TRUE);
